# Generated by Django 3.1.1 on 2025-07-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_gaz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typegaz',
            name='nom',
            field=models.CharField(choices=[('TradexGaz', 'TradexGaz'), ('GPL', 'GPL'), ('SCTM', 'SCTM'), ('TotalEnergies', 'TotalEnergies'), ('Afriquia Gaz', 'Afriquia Gaz'), ('Camgaz', 'Camgaz'), ('GlocalGaz', 'GlocalGaz'), ('Gaz du Cameroun', 'Gaz du Cameroun (GDC)'), ('MRS Cameroon', 'MRS Cameroon'), ('BOCOM Petroleum', 'BOCOM Petroleum')], max_length=50),
        ),
    ]
