# Generated by Django 3.1.1 on 2025-07-22 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_gaz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depot',
            name='proprietaire',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='depot', to=settings.AUTH_USER_MODEL),
        ),
    ]
